name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - snowflake-snowpark-python=
  - streamlit
  - streamlit-echarts
  - streamlit-aggrid
  - streamlit-extras
  - streamlit-option-menu